### ISSUE TITLE
TT5 QT on Windows message writing problem

### ISSUE THREAD

**Issue by adns44** [BearWare/TeamTalk5#1154]
Hi all!

I installed latest 5.8.3.5062 version on Windows 10 Pro 64 bit. I use Qt.

I use JAWS2022. When I typing to message field in chat or in PM, when i press any character, JAWS says x of 512 characters. It is very annoying and makes typing very hard. I experience that synce latest beta install.

Is it possible to add a function that disables that?

**Comment by Oreonan** [comment]
This has been reimplemented. Number of characters is not announce anymore, instead an alert is emit when limit is exceeded and you try to send a message. So it'll be fixed in the next beta.

**Comment by ChrisDuffley** [comment]
'Actually, how does having a character counter next to the text field sound so you can still see how many are in the field in realtime? Good idea for reimplementation though.

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

Sent from my iPhone 12 Pro Max

On Dec 2, 2021, at 07:14, Oreonan ***@***.***> wrote:

﻿
This has been reimplemented. Number of characters is not announce anymore, instead an alert is emit when limit is exceeded and you try to send a message. So it'll be fixed in the next beta.

**Comment by bear101** [comment]
New beta published, so closing issue
