### ISSUE TITLE
Android - Crash when connecting to any server

### ISSUE THREAD

**Issue by CoBC** [BearWare/TeamTalk5#1489]
### Description

With latest beta 5.11.0.5094, TT Android just crash when connecting to any server. In case it's helpful, tested with French language (if recent changes on translation are at origin of this issue.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

TT should connect and work normally.

### Actual behavior

TT crash.

### Steps to reproduce problem

* Connect to a server
* Just see the behavior, client continue to show tabs like you are connected, but you're not.

**Comment by CoBC** [comment]
Apparently not reproduceable with Android 10, reproduceable on Android 12, not tested with 11.

**Comment by Nardol** [comment]
I can reproduce on Android 13.

Firstly when connecting to the server I had the permission dialog to ask about allowing Teamtalk to record audio, I authorized it when using the app then it immediately disconnected with a dialog specifying Teamtalk stop systematically so I taped Close.
Then Authorization to manage and make phone call was asked, why not... But when restarting TeamTalk and select my server the app crashed directly.

P.S. @bear101 do you receive my e-mails? Because I don't receive any answer from you.

**Comment by lbk2907** [comment]
Actually it will login to server just for less than 1 second and it will log out. I'm using Redmi Note 10 Pro running Android 12 with PixelExperience custom rom.

**Comment by Nardol** [comment]
On Android 13 (Pixel 4A) when connecting for the first time with the last beta it crashed.
Second attempt I was connected but I had an alert because the app systematically stops and when taping "Close" it closed.
So I have a different behavior but unfortunately it still crashes.

**Comment by bear101** [comment]
@Nardol I rolled out a new beta today (build 113). Is that the one you're referring to or the one from yesterday (build 112)?

**Comment by Nardol** [comment]
@bear101 I have not this information displayed in the application information but I updated it today so I think it is the build 113.

**Comment by lbk2907** [comment]
Have any way to get the crash log?

**Comment by CoBC** [comment]
@bear101 There is another bug with build 113 on Android 12, when connecting, if you send a private message to the Android client from another client (here Qt client for the test), Android client crash and disconnect from server.

**Comment by bear101** [comment]
I fixed the text message crash in [this](https://github.com/BearWare/TeamTalk5/commit/624569e9212563a8a9201c53a7e7e383c4e6e139) commit. But Bluetooth is also making it crash. For some reason there's a new android.permission.BLUETOOTH_CONNECT permission. Whether this also needs to be obtained, I don't know since we already obtain android.permission.BLUETOOTH. Reading the Android docs doesn't help any.

Unfortunately I don't have an Android 12 device and the issues don't occur in the simulators. My Samsung A10 only supports Android 11.

**Comment by Nardol** [comment]
I had a beta update yesterday, unfortunately it still crashes with my Pixel 4A on Android 13.

**Comment by bear101** [comment]
@Nardol Is it Build 114? When does it crash? Just after connecting?

I'm aware that it crashes on Android 12+ when you upload/download a file.

**Comment by bear101** [comment]
@Nardol There also seem to be a crash issue with Bluetooth.

**Comment by Nardol** [comment]
> Is it Build 114? When does it crash? Just after connecting?

Yes, it is build 114
It crashes just after connecting.

> There also seem to be a crash issue with Bluetooth.

Oh right, when I disable Bluetooth I can connect successfully so the disconnection just after connecting is related to the Bluetooth crash.

**Comment by bear101** [comment]
Build 116 is being pushed now. Please let me know if the Bluetooth issues have been fixed.

**Comment by Nardol** [comment]
@bear101 Fixed for me with a Pixel 4A on Android 13 with Build 116 :+1:
