### ISSUE TITLE
5.7.1 Classic: Saving preferences hangs the client ... sometimes.

### ISSUE THREAD

**Issue by Simon818** [BearWare/TeamTalk5#869]
In the latest classic client, pressing *OK* on the preferences window will sometimes hang the client for a long time. This is similar to the behavior when changing sound devices in 5.7, but also happens when not connected to a server.

One way I was able to reproduce this is by switching my sound events to play all at once, but even this doesn't seem to be reliable. I'm not expecting developers to miraculously be able to reproduce this; I just seem to be the first one to report this and was hoping we could slowly build up more information from other users.

**Comment by ChrisDuffley** [comment]
That is weird, as I've never seen this on my own client. I'll check sometime soon and reply back with my findings.

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On May 10, 2021, at 15:08, Simon Jaeger ***@***.***> wrote:


In the latest classic client, pressing OK on the preferences window will sometimes hang the client for a long time. This is similar to the behavior when changing sound devices in 5.7, but also happens when not connected to a server.

One way I was able to reproduce this is by switching my sound events to play all at once, but even this doesn't seem to be reliable. I'm not expecting developers to miraculously be able to reproduce this; I just seem to be the first one to report this and was hoping we could slowly build up more information from other users.

**Comment by beqabeqa473** [comment]
I can confirm a bug.


freeze happens when saving preferences and in sound events, playback mode all at once is selected
.

i like this option because i can adjust volume of sounds, however if we don't want to get freeze we should change it back for a while.

i tested a test version bjoern has provided, but i didn't think that this could lead to freeze, so i didn't make settings which i had.

**Comment by adns44** [comment]
I have this problem too.

If I use all at once sound playback mode, the client hangs when it plays a sound. For example, when a channel message arrives, or I send an one, my client freezes for a few seconds. The problem disapears when I use One by one mode.

Another same bug, all at once mode uses same sound volume as the master, and one by one has a fix value that irrespective than master volume.
I suggest that add a checkbox to manualy modify it because I prefer All at once with constant volume. I often reduce the master volume but I'd like to hear the incoming channel and private messages sound.

**Comment by smeveriss** [comment]
Hi.
Well, I can confirm this, this happened in  beta build before the stable was released.
It appears to run the default sound device as the internal mic even if I have the main one set to my speaker by default thhough if I go to settings that seems set.
The big issue is that if I hit ok, not only will it hang but it will pull down nvda with it.
The only way to fix this is restart nvda, after which I find the program in a totally crashed state.
This is the error from nvda itself.
ERROR - watchdog._watcher (20:16:10.719) - watchdog (4440):
Core frozen in stack!
INFO - watchdog._watcher (20:16:10.721) - watchdog (4440):
Listing stacks for Python threads:
Python stack for thread 4440 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 142, in _watcher
  File "watchdog.pyc", line 63, in getFormattedStacksForAllThreads

Python stack for thread 2680 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 79, in hookThreadFunc

Python stack for thread 7752 (_UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "_UIAHandler.pyc", line 315, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 13152 (braille._BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "braille.pyc", line 2188, in func

Python stack for thread 11404 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 191, in run
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 11488 (MainThread):
  File "nvda.pyw", line 247, in <module>
  File "core.pyc", line 567, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1067, in Notify
  File "core.pyc", line 536, in run
  File "IAccessibleHandler\__init__.pyc", line 1106, in pumpAll
  File "IAccessibleHandler\__init__.pyc", line 691, in processGenericWinEvent
  File "IAccessibleHandler\__init__.pyc", line 619, in winEventToNVDAEvent
  File "_UIAHandler.pyc", line 720, in isUIAWindow
  File "_UIAHandler.pyc", line 698, in _isUIAWindowHelper

ERROR - watchdog._watcher (20:16:25.775) - watchdog (4440):
Core frozen in stack!
INFO - watchdog._watcher (20:16:25.778) - watchdog (4440):
Listing stacks for Python threads:
Python stack for thread 4440 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 142, in _watcher
  File "watchdog.pyc", line 63, in getFormattedStacksForAllThreads

Python stack for thread 2680 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 79, in hookThreadFunc

Python stack for thread 7752 (_UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "_UIAHandler.pyc", line 315, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 13152 (braille._BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "braille.pyc", line 2188, in func

Python stack for thread 11404 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 191, in run
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 11488 (MainThread):
  File "nvda.pyw", line 247, in <module>
  File "core.pyc", line 567, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1067, in Notify
  File "core.pyc", line 536, in run
  File "IAccessibleHandler\__init__.pyc", line 1106, in pumpAll
  File "IAccessibleHandler\__init__.pyc", line 691, in processGenericWinEvent
  File "IAccessibleHandler\__init__.pyc", line 619, in winEventToNVDAEvent
  File "_UIAHandler.pyc", line 720, in isUIAWindow
  File "_UIAHandler.pyc", line 698, in _isUIAWindowHelper
That itself is not surprising, teamtalk is actually frozen completely and utterly.
Is there a way to generate the actual log of teamtalk and where would the log then be stored.
It is clear by others without a screen reader installed that teamtalk has frozen itself and that means I can't save preffs.
This is not a large issue however as it stands while everything else is set thank goodness I can not save preffs for any reason.
I also can't change sound device on direct sound.
I can get this to happen all the time by the way.
If this continues to happen, I will have to run the previous version at least on portable till this can be fixed else without settings saveable there is a potential problem.
While my speech stopping is not as major as it once was, the fact I can't change settings is a potential issue though as it stands I don't need teamtalk currently and may not need it for a little while on account on the server I used for a spaciffic task currently down after the service it was used for ended its life a couple weeks back.

**Comment by bear101** [comment]
Could this issue be related to a specific screen-reader? If you e.g. use Narrator do you then still have the issue?

**Comment by bear101** [comment]
@Oreonan Have you experienced the issue with NVDA?

**Comment by Oreonan** [comment]
No, I cannot reproduce this for now with NVDA.

I tried differents configurations like direct sound or windows audio 
session, with or without input/output devices, when I save preferences 
it's not crashing the client.

**Comment by beqabeqa473** [comment]
it is crashing when on sound events all at once playback mode is selected

On 5/12/21, Oreonan ***@***.***> wrote:
> No, I cannot reproduce this for now with NVDA.
>
> I tried differents configurations like direct sound or windows audio
> session, with or without input/output devices, when I save preferences
> it's not crashing the client.
>
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/869#issuecomment-839858040


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Oreonan** [comment]
I still not reproduce. What Windows version and sound system 
configuration are used?

**Comment by beqabeqa473** [comment]
windows 10 + wasapi

On 5/12/21, Oreonan ***@***.***> wrote:
> I still not reproduce. What Windows version and sound system
> configuration are used?
>
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/869#issuecomment-839935521


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Oreonan** [comment]
Hmmm, I reproduce if I set "playback mode" to "all at once", I save 
preferences and after I reopen preferences and make a change to "sound 
system" tab, for example enable echo cancellation or select "no sound 
device" to output device. Do you confirm this, or have you another way 
to reproduce?

**Comment by beqabeqa473** [comment]
set playback mode all at once, close clilent, reopen it and try to
select some other input/output device

On 5/12/21, Oreonan ***@***.***> wrote:
> Hmmm, I reproduce if I set "playback mode" to "all at once", I save
> preferences and after I reopen preferences and make a change to "sound
> system" tab, for example enable echo cancellation or select "no sound
> device" to output device. Do you confirm this, or have you another way
> to reproduce?
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/869#issuecomment-839952694


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Oreonan** [comment]
Yes, OK, so with this way I can reproduce. @bear101 it can be probably 
helpfull to debug.

**Comment by bear101** [comment]
Should be fixed now

**Comment by Oreonan** [comment]
I need a SDK test to test this :), unfortunately I don't have take time 
to try to build library on Windows recently.

**Comment by bear101** [comment]
https://bearware.dk/test/teamtalksdk/v5.8.0.5037/

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by beqabeqa473** [comment]
cannot confirm a fix.

still selecting all at once hangs client and only client restart can
be done to continue using it.

also, there is a new bug with this.
when selecting all at once playback mode, there is a big delay of
sound transmission and if i am turning on voice monitoring on myself,
sound goes back after 2 seconds.

On 5/12/21, Oreonan ***@***.***> wrote:
> OK it's apparently fix for me.
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/869#issuecomment-840022837


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Simon818** [comment]
@beqabeqa473 This is not new in the beta. I referenced this in #868; it also causes problems in half-duplex channels, and it doesn't appear to be limited to the "all at once" option--in other words, it always happens no matter which playback mode you select.

**Comment by beqabeqa473** [comment]
yes, it is not new.
it started to appear in v5.7 and if it is not limited to playback
mode, one of causes is playback mode, because if i switch it for
example to interrupt previous, everything works as expected.

On 5/13/21, Simon Jaeger ***@***.***> wrote:
> @beqabeqa473 This is not new in the beta. I referenced this in #868; it also
> causes problems in half-duplex channels, and it doesn't appear to be limited
> to the "all at once" option--in other words, it always happens no matter
> which playback mode you select.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/869#issuecomment-840281872


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
@Simon818 Can you confirm that it is fixed in this version: http://bearware.dk/beta/TeamTalk_v5.8.0.5038_Portable.zip

**Comment by Simon818** [comment]
@bear101 It certainly seems to be. The preferences save and close much more quickly than they ever did in 5.7.1.

**Comment by ChrisDuffley** [comment]
I've noticed this on 5.7.1 and it's still persisting as far as I know. So, I just switched it to Interrupt Previous or One By One and it's all good.

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On May 12, 2021, at 23:27, beqa gozalishvili ***@***.***> wrote:


cannot confirm a fix.

still selecting all at once hangs client and only client restart can
be done to continue using it.

also, there is a new bug with this.
when selecting all at once playback mode, there is a big delay of
sound transmission and if i am turning on voice monitoring on myself,
sound goes back after 2 seconds.

On 5/12/21, Oreonan ***@***.***> wrote:
> OK it's apparently fix for me.
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/869#issuecomment-840022837


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by ChrisDuffley** [comment]
Oh I see what's going on. Hold on, I'll try this in my portable and report back if there's a fix in 5.8.

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On May 16, 2021, at 16:06, ChrisDuffley ***@***.***> wrote:


I've noticed this on 5.7.1 and it's still persisting as far as I know. So, I just switched it to Interrupt Previous or One By One and it's all good.

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On May 12, 2021, at 23:27, beqa gozalishvili ***@***.***> wrote:


cannot confirm a fix.

still selecting all at once hangs client and only client restart can
be done to continue using it.

also, there is a new bug with this.
when selecting all at once playback mode, there is a big delay of
sound transmission and if i am turning on voice monitoring on myself,
sound goes back after 2 seconds.

On 5/12/21, Oreonan ***@***.***> wrote:
> OK it's apparently fix for me.
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/869#issuecomment-840022837


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili
